#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          order-service-client:
#            client-id: sahib
#            client-secret: sahib123
#            scope: read
#            authorization-grant-type: client_credentials
#            provider: keycloak
#        provider:
#          keycloak:
#            token-uri: http://auth-server-domain/token
